dtbo-$(CONFIG_CPU_RK3399) += seco-rk3399-c31-hdmi.dtbo \
				seco-rk3399-c31-sn65dsi84.dtbo 

targets += dtbs dtbs_install
targets += $(dtbo-y)

always          := $(dtbo-y)
clean-files     := *.dtbo

